#!/bin/bash

#input FP exec
FP_exec=$1

echo FP_exec=$FP_exec
echo $FLEXOUT_TMP
suffix=$(date "+%y-%m-%d_%H%M%S")
test_tmp=${FLEXOUT_TMP}test_1_$suffix
current_dir=$(pwd)
echo test_tmp=$test_tmp
mkdir $test_tmp


cp -r test_1/options $test_tmp
cp test_1/pathnames $test_tmp
cp test_1/run $test_tmp

cd $test_tmp

./run $FP_exec  &> $test_tmp.log #&



